eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9006
spring:
  application:
    name: hongguan-data
  datasource:
    username: root
    password: 123456
    #url: jdbc:mysql://localhost:3306/performance_schema
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    show-sql: true
#    database: mysql
mybatis:
  type-aliases-package: com.hg.data.entity
