eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9999
spring:
  application:
    name: hongguan-vue
  mvc:
    static-path-pattern: /**
    view:
      suffix: .html
      prefix: /
  # 修改默认的静态寻址资源目录 多个使用逗号分隔
  resources:
    static-locations: classpath:/META-INF/resources/,
      classpath:/resources/,
      classpath:/static/,
      classpath:/public/,
      classpath:/itstyle/